### ISSUE TITLE
Allow for prefixed tags

### ISSUE THREAD

**Issue by orf** [mislav/bump-homebrew-formula-action#18]
When using [cargo release](https://github.com/sunng87/cargo-release) with a Rust workspace (i.e one containing multiple projects) the tags are created as `[proj-name]-[version]`. For example: `gping-v1.2.3`.

This unfortunately causes this action to not work ([see here](https://github.com/orf/gping/runs/3108981656?check_suite_focus=true)), as it says `Skipping: the formula version 'v1.2.1' is newer than 'gping-v1.2.3'`.

Is there a way around this? Perhaps by supplying some kind of regex to extract the version and ignore the prefix?

**Comment by mislav** [comment]
Thanks for reporting! I'm not sure how to fix this. Here is our version-related code: https://github.com/mislav/bump-homebrew-formula-action/blob/main/src/version.ts

> Perhaps by supplying some kind of regex to extract the version and ignore the prefix?

That sounds like a plausible approach, but how to expose this while at the same time making it easy to use?

**Comment by nitrocode** [comment]
Maybe expose the regex as an input and retain its current value as the default? Would that work?

https://github.com/mislav/bump-homebrew-formula-action/blob/2958320c8b50c846c08a7c0c71da9e6745481834/src/version.ts#L3

**Comment by john-u** [comment]
We ran into this issue as well and are unable to use it currently so I started a draft PR #38.

**Comment by mislav** [comment]
I've finally taken a long look into this, and the problem of prefixed tags doesn't seem so hard.

@john-u Thanks for reporting your case. In the scenario of `smartthings` download URLs, the version parser failed to account that your tag names might have the `/` character in them. This is now fixed.

@orf In the case of tag names such as `gping-v1.2.3`, this project should already work even though the version numbers are "prefixed". Our version comparison function doesn't care if the tag is prefixed or not; it will simply compare e.g. `gping-v1.13.2` to `gping-v1.14.0` and determine that the latter is the newer version. However, it will fail when comparing non-prefixed version numbers such as `v.1.14` to `gping-v1.13.0`. Since your git tag names are always prefixed, I'm not sure how it happened in the first place that a non-prefixed version number was used in comparison. When this happens again, please post the YAML setup of the workflow that uses this action. Thanks!
