### ISSUE TITLE
`invalid ref: refs/heads/master` while using the action.

### ISSUE THREAD

**Issue by gaetschwartz** [mislav/bump-homebrew-formula-action#47]
Hi,

While trying to use the action, I'm getting `invalid ref: refs/heads/master`. I'm not sure to understand exactly why. 

Here is the workflow run if you need more details:
https://github.com/gaetschwartz/zvm/actions/runs/4158354170/jobs/7193510713

**Comment by mislav** [comment]
Hi, I count a lot of things wrong in your setup:
1. In your workflow, you don't need steps `Clone zvm`, `Set up Homebrew`, nor `Extract formula path`;
2. You set `tag-name` as an exported environment variable in `echo "tag-name=$tag_name" >> $GITHUB_ENV`, but later you try to access it as a step output `${{ steps.extract-version.outputs.tag-name }}`. Step outputs are not environment variables. Please refer to Actions documentation to learn how to create step outputs;
3. `formula-path` is the relative path to your formula file in your tap repository. That would be `formula-path: zvm.rb` in your case;
4. `homebrew-tap` is the literal name of the GitHub repository where you want to update the formula. That would be `homebrew-tap: gaetschwartz/homebrew-zvm` in your case (Homebrew CLI lets you omit the `homebrew-` part, but not this Action);
5. `base-branch` in your homebrew tap repo is `main` not `master`, but you don't have to set this parameter at all, because it will default to the main branch anyway;
6. Please ensure that the `HOMEBREW_GITHUB_API_TOKEN` secret is a token with write access to the `gaetschwartz/homebrew-zvm` repo.
