### ISSUE TITLE
Does this create a formula if it doesn't already exist?

### ISSUE THREAD

**Issue by FollowTheProcess** [mislav/bump-homebrew-formula-action#49]
Hello!

Just trying to get a release workflow for a rust project template I'm working on and after spending all day figuring out cross-compiling, my last hurdle is updating my homebrew tap (I miss GoReleaser!).

I've tried the action out in a [test repo](https://github.com/FollowTheProcess/brewtest) to develop the [workflow](https://github.com/FollowTheProcess/brewtest/blob/b1e33acaea89fa426f37d961194520caaa54b2fc/.github/workflows/CI.yml#L104) but I get the following error:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/62767721/219964193-c50f0dd6-6a47-42b5-8b47-ffc5b3baf3b4.png">

I'm guessing this action can only _update_ an existing formula, not create a new one from scratch? Is there any way of doing this or am I barking up the wrong tree?

I've also tried https://github.com/marketplace/actions/homebrew-releaser but got a weird `is a directory` error when it was generating the SHA256 for the tarball 🙁.

**Comment by mislav** [comment]
Hi! Unfortunately for you, this project only aims to upgrade existing formulae. It cannot generate a new one.

Bumping version numbers and checksums in existing formulae is sometimes that happens often and can be time-consuming and error-prone. This project solves that. Creating a new Homebrew formula and submitting that as a PR is in my opinion best done by hand, but fortunately is not required too often (at most once per project).

Both `homebrew-releaser` and GoReleaser regenerate an entire Homebrew formula from scratch on each release. This has a benefit of working equally well for both creating a formula and keeping it updated later, but is designed for maintaining your own Homebrew taps (separate repositories with your own formulae). The generated formulae are not guaranteed to be compatible with `homebrew-core`, Homebrew's main and default tap repository. By contrast, this project was designed to always be compatible with `homebrew-core` (since it only updates values in certain fields and nothing more), but can be used to keep formula in your own taps updated.

**Comment by FollowTheProcess** [comment]
Fair enough! Thanks for the quick reply! Sounds like an excuse to hack together my own version 🤓
